name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd domains/cvdelapantiga.info/public_html/sppd_bpkad
            if [ ! -d ".git" ]; then
              git init -b main
              git remote add origin https://github.com/Hikuroshi/sppd_bpkad_laravel_10
            fi
            rm -f .git/index.lock
            git fetch origin main
            git reset --hard origin/main
            git clean -f -d
            php composer.phar install --ignore-platform-reqs
            chmod -R 777 storage bootstrap/cache
            php -r "file_exists('.env') || copy('.env.example', '.env');"
            php artisan key:generate
            sed -i "s/DB_DATABASE=.*/DB_DATABASE=${{ secrets.DB_DATABASE }}/g" .env
            sed -i "s/DB_USERNAME=.*/DB_USERNAME=${{ secrets.DB_USERNAME }}/g" .env
            sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=${{ secrets.DB_PASSWORD }}/g" .env
